ALTER TABLE "UserProfile"
ADD COLUMN "baseCurrency" TEXT NOT NULL DEFAULT 'GHS',
ADD COLUMN "preferredCurrency" TEXT NOT NULL DEFAULT 'GHS',
ADD COLUMN "budgetStartMode" TEXT NOT NULL DEFAULT 'CURRENT_MONTH';

ALTER TABLE "BudgetTarget"
ADD COLUMN "cadence" TEXT NOT NULL DEFAULT 'MONTHLY';
